### ISSUE TITLE
Lightweight linux

### ISSUE THREAD

**Issue by TheBdouilleur** [TheBdouilleur/je-repos#2]

**Comment by TheBdouilleur** [comment]
[@TheBdouilleur2]()
pour la live usb installation : [Rufus](https://rufus.ie/fr_FR.html)
Pour la tour: sparky linux  (https://sourceforge.net/projects/sparkylinux/files/base/sparkylinux-5.8-i686-minimalgui.iso/download)
Pour le portable : Peppermint OS (https://peppermintos.com/)

**Comment by TheBdouilleur2** [comment]
Merci beaucoup.

**Comment by TheBdouilleur2** [comment]
J'ai un problème sur le portable: gparted ne trouve pas le disque dur, il ne trouve que la clée.

**Comment by TheBdouilleur2** [comment]
Je crois que je vais détruire les deux, as tu des sugestions de chose à faires?

**Comment by TheBdouilleur** [comment]
what? détruire quoi? jpeux avoir une photo de gparted en train de bugger?

**Comment by TheBdouilleur** [comment]
[@TheBdouilleur2]()
pour la live usb installation : [Rufus](https://rufus.ie/fr_FR.html)
Pour la tour: sparky linux  (https://sourceforge.net/projects/sparkylinux/files/base/sparkylinux-5.8-i686-minimalgui.iso/download)
Pour le portable : Peppermint OS (https://peppermintos.com/)

**Comment by TheBdouilleur** [comment]
comment tu fais pour les messages?
et by the way, regarde ca ( pour heberger tonsite de je)

**Comment by TheBdouilleur** [comment]
je viens de commencer a suivre un cours mozilla : https://developer.mozilla.org/fr/docs/Learn/Server-side/Django/Introduction

**Comment by TheBdouilleur2** [comment]
Le cours à l'air génial.

**Comment by TheBdouilleur2** [comment]
Quant à moi, j'ai trouvé un site d'actualitées tech: https://techmoka.com

**Comment by TheBdouilleur2** [comment]
gparted marche très bien, le dique dur n'est juste pas reconue comme un peripherique.

**Comment by TheBdouilleur2** [comment]
J'ai créé un  repos avec un projet de site web des J-E.

**Comment by TheBdouilleur** [comment]
pages.github.com

**Comment by TheBdouilleur** [comment]
Hi! Can you autorisees pe to commit changes directly to je repos web?

**Comment by TheBdouilleur** [comment]
https://top5hosting.co.uk/blog/uk-hosting/356-how-to-turn-your-old-pc-into-a-linux-ubuntu-server

**Comment by TheBdouilleur** [comment]
check ca c'est un tuto pour mettre le site des je sur internet gratuitement
